excluded: # paths to ignore during linting. Takes precedence over included.
  - Pods
  - vendor
  - PlantasiaUnitTests

disabled_rules:
  - block_based_kvo
  - discarded_notification_center_observer
  - trailing_whitespace
  - todo
  - identifier_name
  - implicit_getter
  - valid_ibinspectable
  - void_function_in_ternary

opt_in_rules:
  - attributes
  - closure_spacing
  - contains_over_first_not_nil
  - empty_count
  - fatal_error_message
  - joined_default_parameter
  - literal_expression_end_indentation
  - overridden_super_call
  - override_in_extension
  - redundant_nil_coalescing
  - unneeded_parentheses_in_closure_argument
  - yoda_condition
  - empty_string
  - first_where
  - modifier_order
  - private_outlet
  - sorted_imports
  - toggle_bool
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - force_unwrapping
  - implicit_return

#explicit set of warning level
line_length: 170
file_length: 800
type_name:
  max_length: 50
type_body_length: 300
force_cast: error
function_parameter_count: 7
attributes:
  attributes_with_arguments_always_on_line_above: false
function_parameter_count: 10
